// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace MyGame
{

using global::System;
using global::FlatBuffers;

public struct PolarPoint : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public PolarPoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Mag { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public void MutateMag(float mag) { __p.bb.PutFloat(__p.bb_pos + 0, mag); }
  public float Arg { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public void MutateArg(float arg) { __p.bb.PutFloat(__p.bb_pos + 4, arg); }

  public static Offset<MyGame.PolarPoint> CreatePolarPoint(FlatBufferBuilder builder, float Mag, float Arg) {
    builder.Prep(4, 8);
    builder.PutFloat(Arg);
    builder.PutFloat(Mag);
    return new Offset<MyGame.PolarPoint>(builder.Offset);
  }
};


}
