# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MyGame

import flatbuffers

class PolarPoint(object):
    __slots__ = ['_tab']

    # PolarPoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PolarPoint
    def Mag(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # PolarPoint
    def Arg(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreatePolarPoint(builder, mag, arg):
    builder.Prep(4, 8)
    builder.PrependFloat32(arg)
    builder.PrependFloat32(mag)
    return builder.Offset()
