// automatically generated by the FlatBuffers compiler, do not modify

package MyGame;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Transformation extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Transformation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float scale() { return bb.getFloat(bb_pos + 0); }
  public void mutateScale(float scale) { bb.putFloat(bb_pos + 0, scale); }
  public float angle() { return bb.getFloat(bb_pos + 4); }
  public void mutateAngle(float angle) { bb.putFloat(bb_pos + 4, angle); }

  public static int createTransformation(FlatBufferBuilder builder, float scale, float angle) {
    builder.prep(4, 8);
    builder.putFloat(angle);
    builder.putFloat(scale);
    return builder.offset();
  }
}

