# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MyGame

import flatbuffers

class Transformation(object):
    __slots__ = ['_tab']

    # Transformation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Transformation
    def Scale(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Transformation
    def Angle(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateTransformation(builder, scale, angle):
    builder.Prep(4, 8)
    builder.PrependFloat32(angle)
    builder.PrependFloat32(scale)
    return builder.Offset()
